version: 2
jobs:
  build:
    docker:
      # we don't use here the default circleci node images because when installing salto we run go
      # this should be changed once salesforce-adapter is depended only salto-adapter-api or when salto 
      # is published to npm (and not depended via github)
      - image: saltolabs/salto:0.0.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run:
          name: Run Jest tests
          command: npx jest --ci --runInBand --forceExit --coverage --verbose --detectOpenHandles --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports
      
      # Code coverage
      - run:
          name: Upload coverage to codecov.io
          command: npx codecov -f coverage/*.json


